package crsAppPackage;
import javax.swing.JOptionPane;
import javax.swing.JDialog;
import javax.swing.SwingUtilities;
import java.awt.Dialog;


public class CourseRecoveryPlanFrame extends javax.swing.JFrame {
    
    private CourseRecoveryPlan CRPcontroller;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CourseRecoveryPlanFrame.class.getName());

    /**
     * Creates new form main_course_recovery_plan_frame
     */
    public CourseRecoveryPlanFrame() {
        initComponents();
        CRPcontroller = new CourseRecoveryPlan();
        refreshData();
    }
    
    public void refreshData() {
        jTable_Student_Failed.setModel(CRPcontroller.loadFailedStudentsTable());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_Student_Failed = new javax.swing.JPanel();
        jScrollPanel_Student_Failed = new javax.swing.JScrollPane();
        jTable_Student_Failed = new javax.swing.JTable();
        jTF_SearchIDName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jBtnEditPlan = new javax.swing.JButton();
        jBtnDeletePlan = new javax.swing.JButton();
        jBtnTrackPlan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable_Student_Failed.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Major", "CGPA", "Year", "Email"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable_Student_Failed.setName("list_student_failed"); // NOI18N
        jScrollPanel_Student_Failed.setViewportView(jTable_Student_Failed);
        jTable_Student_Failed.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        javax.swing.GroupLayout jPanel_Student_FailedLayout = new javax.swing.GroupLayout(jPanel_Student_Failed);
        jPanel_Student_Failed.setLayout(jPanel_Student_FailedLayout);
        jPanel_Student_FailedLayout.setHorizontalGroup(
            jPanel_Student_FailedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPanel_Student_Failed, javax.swing.GroupLayout.DEFAULT_SIZE, 638, Short.MAX_VALUE)
        );
        jPanel_Student_FailedLayout.setVerticalGroup(
            jPanel_Student_FailedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Student_FailedLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPanel_Student_Failed, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTF_SearchIDName.setText("Search here...");
        jTF_SearchIDName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTF_SearchIDNameFocusGained(evt);
            }
        });
        jTF_SearchIDName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTF_SearchIDNameActionPerformed(evt);
            }
        });

        jLabel3.setText("Search by Student ID or Name");

        jBtnEditPlan.setLabel("Add/Edit Plan");
        jBtnEditPlan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnEditPlanActionPerformed(evt);
            }
        });

        jBtnDeletePlan.setLabel("Delete Plan");
        jBtnDeletePlan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnDeletePlanActionPerformed(evt);
            }
        });

        jBtnTrackPlan.setActionCommand("Track");
        jBtnTrackPlan.setLabel("Track Plan");
        jBtnTrackPlan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnTrackPlanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBtnTrackPlan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBtnEditPlan)
                        .addGap(18, 18, 18)
                        .addComponent(jBtnDeletePlan))
                    .addComponent(jPanel_Student_Failed, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTF_SearchIDName, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTF_SearchIDName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel_Student_Failed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnEditPlan)
                    .addComponent(jBtnDeletePlan)
                    .addComponent(jBtnTrackPlan))
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTF_SearchIDNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTF_SearchIDNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTF_SearchIDNameActionPerformed

    private void jTF_SearchIDNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTF_SearchIDNameFocusGained
    if (jTF_SearchIDName.getText().equals("Search here...")) {
        jTF_SearchIDName.setText("");
        }
    }//GEN-LAST:event_jTF_SearchIDNameFocusGained

    private void jBtnTrackPlanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnTrackPlanActionPerformed
        // 1. Ambil row yang dipilih
        int selectedRow = jTable_Student_Failed.getSelectedRow();

        // 2. Validasi: belum pilih row
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(
                this,
                "Please select a recovery plan first.",
                "No Selection",
                JOptionPane.WARNING_MESSAGE
            );
            return;
        }

        // 3. Ambil recoveryId dari kolom 0
        String recoveryId =
                jTable_Student_Failed.getValueAt(selectedRow, 5).toString();
                    String mode;
            if(recoveryId.equals(0)){
                mode = "Add";
            } else{
                mode = "Update";
            }

        // 4. Buat panel details (kamu SUDAH punya ini)
        CourseRecoveryPlanDetailsPanel detailsPanel = new CourseRecoveryPlanDetailsPanel(recoveryId,"Track",mode);

        // 5. Tampilkan panel (pilih salah satu cara di bawah)

        // === CARA A: tampil di dialog (PALING AMAN) ===
        JDialog dialog = new JDialog(
                SwingUtilities.getWindowAncestor(this),
                "Recovery Plan Details",
                Dialog.ModalityType.APPLICATION_MODAL
        );
        dialog.setContentPane(detailsPanel);
        dialog.pack();
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);
    }//GEN-LAST:event_jBtnTrackPlanActionPerformed

    private void jBtnEditPlanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnEditPlanActionPerformed
            // 1. Ambil row yang dipilih
            int selectedRow = jTable_Student_Failed.getSelectedRow();

            // 2. Validasi: belum pilih row
            if (selectedRow == -1) {
                JOptionPane.showMessageDialog(
                    this,
                    "Please select a recovery plan first.",
                    "No Selection",
                    JOptionPane.WARNING_MESSAGE
                );
                return;
            }

            // 3. Ambil recoveryId dari kolom 0
            String recoveryId =
                    jTable_Student_Failed.getValueAt(selectedRow, 5).toString();
            String mode;
            if(recoveryId.equals(0)){
                mode = "Add";
            } else{
                mode = "Update";
            }

            // 4. Buat panel details (kamu SUDAH punya ini)
            CourseRecoveryPlanDetailsPanel detailsPanel = new CourseRecoveryPlanDetailsPanel(recoveryId,"Edit", mode);

            // 5. Tampilkan panel (pilih salah satu cara di bawah)

            // === CARA A: tampil di dialog (PALING AMAN) ===
            JDialog dialog = new JDialog(
                    SwingUtilities.getWindowAncestor(this),
                    "Recovery Plan Details",
                    Dialog.ModalityType.APPLICATION_MODAL
            );
            dialog.setContentPane(detailsPanel);
            dialog.pack();
            dialog.setLocationRelativeTo(this);
            dialog.setVisible(true);
    }//GEN-LAST:event_jBtnEditPlanActionPerformed

    private void jBtnDeletePlanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDeletePlanActionPerformed
    int selectedRow = jTable_Student_Failed.getSelectedRow();

       if (selectedRow == -1) {
           JOptionPane.showMessageDialog(
               this,
               "Please select a recovery plan to delete.",
               "No Selection",
               JOptionPane.WARNING_MESSAGE
           );
           return;
       }

       String recoveryId =
               jTable_Student_Failed.getValueAt(selectedRow, 5).toString();
        System.out.println(recoveryId);
       int confirm = JOptionPane.showConfirmDialog(
               this,
               "Are you sure you want to delete Recovery Plan " + recoveryId + "?",
               "Confirm Delete",
               JOptionPane.YES_NO_OPTION
       );

       if (confirm != JOptionPane.YES_OPTION) {
           return;
       }

       // === CALL CONTROLLER ===
       CourseRecoveryPlan controller = new CourseRecoveryPlan();
       controller.deleteRecoveryPlan(recoveryId);

       // === REFRESH TABLE ===
       refreshData(); // method kamu yang reload JTable
    }//GEN-LAST:event_jBtnDeletePlanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CourseRecoveryPlanFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnDeletePlan;
    private javax.swing.JButton jBtnEditPlan;
    private javax.swing.JButton jBtnTrackPlan;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel_Student_Failed;
    private javax.swing.JScrollPane jScrollPanel_Student_Failed;
    private javax.swing.JTextField jTF_SearchIDName;
    private javax.swing.JTable jTable_Student_Failed;
    // End of variables declaration//GEN-END:variables
}
