package crsAppPackage;

public class CourseRecoveryPlanFrame extends javax.swing.JFrame {
    
    private CourseRecoveryPlan CRPcontroller;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CourseRecoveryPlanFrame.class.getName());

    /**
     * Creates new form main_course_recovery_plan_frame
     */
    public CourseRecoveryPlanFrame() {
        initComponents();
        CRPcontroller = new CourseRecoveryPlan();
        loadTable();
    }
    
    private void loadTable() {
        jTable_Student_Failed.setModel(CRPcontroller.loadFailedStudentsTable(false));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_Student_Failed = new javax.swing.JPanel();
        jScrollPanel_Student_Failed = new javax.swing.JScrollPane();
        jTable_Student_Failed = new javax.swing.JTable();
        jTF_SearchIDName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton_Plan_Editor = new javax.swing.JButton();
        jButton_Milestone = new javax.swing.JButton();
        jButton_Milestone1 = new javax.swing.JButton();
        jCB_Batch_Edit = new javax.swing.JCheckBox();
        jButton_Milestone2 = new javax.swing.JButton();
        jButton_Milestone3 = new javax.swing.JButton();
        jButton_Milestone4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable_Student_Failed.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Major", "CGPA", "Year", "Email"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable_Student_Failed.setName("list_student_failed"); // NOI18N
        jScrollPanel_Student_Failed.setViewportView(jTable_Student_Failed);
        jTable_Student_Failed.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        javax.swing.GroupLayout jPanel_Student_FailedLayout = new javax.swing.GroupLayout(jPanel_Student_Failed);
        jPanel_Student_Failed.setLayout(jPanel_Student_FailedLayout);
        jPanel_Student_FailedLayout.setHorizontalGroup(
            jPanel_Student_FailedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPanel_Student_Failed, javax.swing.GroupLayout.DEFAULT_SIZE, 638, Short.MAX_VALUE)
        );
        jPanel_Student_FailedLayout.setVerticalGroup(
            jPanel_Student_FailedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Student_FailedLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPanel_Student_Failed, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        jTF_SearchIDName.setText("Search here...");
        jTF_SearchIDName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTF_SearchIDNameFocusGained(evt);
            }
        });
        jTF_SearchIDName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTF_SearchIDNameActionPerformed(evt);
            }
        });

        jLabel3.setText("Search by Student ID or Name");

        jButton_Plan_Editor.setLabel("Delete Plan");

        jButton_Milestone.setLabel("Add Plan");
        jButton_Milestone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_MilestoneActionPerformed(evt);
            }
        });

        jButton_Milestone1.setLabel("Edit Plan");

        jCB_Batch_Edit.setText("Multiple Select");
        jCB_Batch_Edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCB_Batch_EditActionPerformed(evt);
            }
        });

        jButton_Milestone2.setLabel("Failed");

        jButton_Milestone3.setLabel("Ongoing");

        jButton_Milestone4.setLabel("Pass");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jCB_Batch_Edit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton_Milestone1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_Milestone2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton_Milestone, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton_Plan_Editor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton_Milestone3, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton_Milestone4, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jPanel_Student_Failed, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTF_SearchIDName, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTF_SearchIDName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addComponent(jPanel_Student_Failed, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton_Milestone2)
                            .addComponent(jButton_Milestone3)
                            .addComponent(jButton_Milestone4))
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton_Plan_Editor)
                            .addComponent(jButton_Milestone)
                            .addComponent(jButton_Milestone1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jCB_Batch_Edit)))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCB_Batch_EditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCB_Batch_EditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCB_Batch_EditActionPerformed

    private void jTF_SearchIDNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTF_SearchIDNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTF_SearchIDNameActionPerformed

    private void jTF_SearchIDNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTF_SearchIDNameFocusGained
    if (jTF_SearchIDName.getText().equals("Search here...")) {
        jTF_SearchIDName.setText("");
        }
    }//GEN-LAST:event_jTF_SearchIDNameFocusGained

    private void jButton_MilestoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_MilestoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_MilestoneActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CourseRecoveryPlanFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Milestone;
    private javax.swing.JButton jButton_Milestone1;
    private javax.swing.JButton jButton_Milestone2;
    private javax.swing.JButton jButton_Milestone3;
    private javax.swing.JButton jButton_Milestone4;
    private javax.swing.JButton jButton_Plan_Editor;
    private javax.swing.JCheckBox jCB_Batch_Edit;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel_Student_Failed;
    private javax.swing.JScrollPane jScrollPanel_Student_Failed;
    private javax.swing.JTextField jTF_SearchIDName;
    private javax.swing.JTable jTable_Student_Failed;
    // End of variables declaration//GEN-END:variables
}
