package crsAppPackage;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author gilan
 */
public class CourseRecoveryPlanDetailsPanel extends javax.swing.JPanel {

    private CourseRecoveryPlanDetails CRPDetailsController;
    
    private final string studentID;

    /**
     * Creates new form CourseRecoveryPlanSummary
     */
    public CourseRecoveryPlanDetailsPanel(string studentID) {
        initComponents();
        CRPDetailsController = new CourseRecoveryPlanDetails();
        refresh();
    }

    private void refresh(){
        jTable_recoveryplandetails.setModel(CRPDetailsController.refreshTable());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_recoveryplandetails = new javax.swing.JTable();
        jBtnOngoing = new javax.swing.JButton();
        jBtnFailed = new javax.swing.JButton();
        jBtnPass = new javax.swing.JButton();
        jLblTitle = new javax.swing.JLabel();
        JLblSubtitle = new javax.swing.JLabel();
        jBtnPass1 = new javax.swing.JButton();
        jBtnPass2 = new javax.swing.JButton();

        jTable_recoveryplandetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Week", "Task Description", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable_recoveryplandetails);

        jBtnOngoing.setLabel("Mark Ongoing");

        jBtnFailed.setLabel("Mark Failed");
        jBtnFailed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnFailedActionPerformed(evt);
            }
        });

        jBtnPass.setLabel("Mark Pass");

        jLblTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLblTitle.setText("Recovery Plan & Milestone");

        JLblSubtitle.setText("Select one plan to change status");

        jBtnPass1.setLabel("Save");
        jBtnPass1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPass1ActionPerformed(evt);
            }
        });

        jBtnPass2.setLabel("Cancel");
        jBtnPass2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPass2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBtnFailed, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(jBtnOngoing, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                        .addComponent(jBtnPass, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JLblSubtitle)
                            .addComponent(jLblTitle))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBtnPass1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jBtnPass2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLblTitle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JLblSubtitle))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBtnPass1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBtnPass2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnOngoing, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnFailed, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnPass, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnFailedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnFailedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnFailedActionPerformed

    private void jBtnPass1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPass1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnPass1ActionPerformed

    private void jBtnPass2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPass2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnPass2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLblSubtitle;
    private javax.swing.JButton jBtnFailed;
    private javax.swing.JButton jBtnOngoing;
    private javax.swing.JButton jBtnPass;
    private javax.swing.JButton jBtnPass1;
    private javax.swing.JButton jBtnPass2;
    private javax.swing.JLabel jLblTitle;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_recoveryplandetails;
    // End of variables declaration//GEN-END:variables
}
