package crsAppPackage;
import javax.swing.*;
import java.awt.Dialog;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import javax.swing.JTable;
import javax.swing.table.TableColumn;
import javax.swing.table.TableCellRenderer;
import java.awt.Component;

public class FailedStudentListFrame extends javax.swing.JFrame
    implements CRPView {

    private FailedStudentListController controller;
    private DefaultTableModel tableModel;
    private List<StudentAcademicProfile> failedStudents;


    public FailedStudentListFrame() {
        this.controller = new FailedStudentListController();
        initComponents();

        setDefaultTableFormat();
        loadTableData();
        addRowClickListener();
        autoResizeAllColumns(jTable_Student_Failed);
    }

    @Override
    public void loadTableData() {
        tableModel.setRowCount(0);
        failedStudents = controller.getFailedStudents();

// was used for debugging only
//        for (StudentAcademicProfile s : failed) {
//            System.out.println(s.getStudentID());
//            System.out.println(s.getStudentName());
//            System.out.println(s.getStudentMajor());
//            System.out.println(s.calculateCGPA());
//            System.out.println(s.getStudentYear());
//            System.out.println(s.getStudentEmail());
//        }

        for (StudentAcademicProfile s : failedStudents) {
                tableModel.addRow(new Object[]{
                    s.getStudentID(),
                    s.getStudentName(),
                    s.getStudentMajor(),
                    String.format("%.2f", s.calculateCGPA()),
                    s.getStudentYear(),
                    s.getStudentEmail()
                });
        }
    }
    
    @Override
    public void setDefaultTableFormat() {
        tableModel = new DefaultTableModel(
            new Object[]{"Student ID", "Name", "Major", "CGPA", "Year", "Email"}, 0
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        jTable_Student_Failed.setModel(tableModel);
    }
    
    @Override
    public void cancelChanges(){};
    
    @Override
    public void saveData(){};
    
    private void addRowClickListener() {
        jTable_Student_Failed.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                if (evt.getClickCount() == 2) { // double-click
                    int row = jTable_Student_Failed.getSelectedRow();

                    if (row >= 0) {
                        StudentAcademicProfile selectedStudent =
                            failedStudents.get(row);

                        openCourseRecoveryPlan(selectedStudent);
                    }
                }
            }
        });
    }
    
    private void openCourseRecoveryPlan(StudentAcademicProfile student) {
        CourseRecoveryPlanFrame frame =
            new CourseRecoveryPlanFrame(student);

        frame.setLocationRelativeTo(this); 
        frame.setVisible(true);
    }

    private void autoResizeAllColumns(JTable table) {
        for (int col = 0; col < table.getColumnCount(); col++) {
            autoResizeColumn(table, col);
        }
    }

    private void autoResizeColumn(JTable table, int column) { 
        TableColumn tableColumn = table.getColumnModel().getColumn(column);

        int preferredWidth = tableColumn.getMinWidth();
        int maxWidth = tableColumn.getMaxWidth();

        // Header width
        TableCellRenderer headerRenderer = table.getTableHeader().getDefaultRenderer();
        Component headerComp = headerRenderer.getTableCellRendererComponent(
                table, tableColumn.getHeaderValue(), false, false, 0, column);

        preferredWidth = Math.max(preferredWidth, headerComp.getPreferredSize().width);

        // Cell width
        for (int row = 0; row < table.getRowCount(); row++) {
            TableCellRenderer cellRenderer = table.getCellRenderer(row, column);
            Component cellComp = table.prepareRenderer(cellRenderer, row, column);
            preferredWidth = Math.max(preferredWidth, cellComp.getPreferredSize().width);
        }

        tableColumn.setPreferredWidth(Math.min(preferredWidth + 10, maxWidth));
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_Student_Failed = new javax.swing.JPanel();
        jScrollPanel_Student_Failed = new javax.swing.JScrollPane();
        jTable_Student_Failed = new javax.swing.JTable();
        tfSearchBar = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnViewCourseRecoveryPlan = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jBtnClose = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable_Student_Failed.setAutoCreateRowSorter(true);
        jTable_Student_Failed.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Major", "CGPA", "Year", "Email"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable_Student_Failed.setName("list_student_failed"); // NOI18N
        jTable_Student_Failed.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        jScrollPanel_Student_Failed.setViewportView(jTable_Student_Failed);
        jTable_Student_Failed.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        javax.swing.GroupLayout jPanel_Student_FailedLayout = new javax.swing.GroupLayout(jPanel_Student_Failed);
        jPanel_Student_Failed.setLayout(jPanel_Student_FailedLayout);
        jPanel_Student_FailedLayout.setHorizontalGroup(
            jPanel_Student_FailedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPanel_Student_Failed, javax.swing.GroupLayout.DEFAULT_SIZE, 637, Short.MAX_VALUE)
        );
        jPanel_Student_FailedLayout.setVerticalGroup(
            jPanel_Student_FailedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_Student_FailedLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPanel_Student_Failed, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tfSearchBar.setText("Search here...");
        tfSearchBar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfSearchBarFocusGained(evt);
            }
        });
        tfSearchBar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfSearchBarActionPerformed(evt);
            }
        });
        tfSearchBar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfSearchBarKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfSearchBarKeyReleased(evt);
            }
        });

        jLabel3.setText("Search by Name");

        btnViewCourseRecoveryPlan.setText("View Course Recovery Plan");
        btnViewCourseRecoveryPlan.setActionCommand("Track");
        btnViewCourseRecoveryPlan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewCourseRecoveryPlanActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Failed Student List");

        jBtnClose.setText("Close");
        jBtnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBtnClose))
                    .addComponent(jPanel_Student_Failed, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfSearchBar, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(btnViewCourseRecoveryPlan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jBtnClose))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfSearchBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel_Student_Failed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnViewCourseRecoveryPlan, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfSearchBarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfSearchBarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfSearchBarActionPerformed

    private void tfSearchBarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfSearchBarFocusGained
    if (tfSearchBar.getText().equals("Search here...")) {
        tfSearchBar.setText("");
        }
    
    }//GEN-LAST:event_tfSearchBarFocusGained

    private void btnViewCourseRecoveryPlanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewCourseRecoveryPlanActionPerformed
        int selectedRow = jTable_Student_Failed.getSelectedRow();
        
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(
                this,
                "Please select a student first.",
                "No Student Selected",
                JOptionPane.WARNING_MESSAGE
            );
            return;
        }

        StudentAcademicProfile selectedStudent =
            failedStudents.get(selectedRow);

        CourseRecoveryPlanFrame frame =
            new CourseRecoveryPlanFrame(selectedStudent);

        frame.setLocationRelativeTo(this); // center relatif ke frame ini
        frame.setVisible(true);
    }//GEN-LAST:event_btnViewCourseRecoveryPlanActionPerformed

    private void jBtnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCloseActionPerformed
        this.dispose();
    }//GEN-LAST:event_jBtnCloseActionPerformed

    private void tfSearchBarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfSearchBarKeyPressed
    }//GEN-LAST:event_tfSearchBarKeyPressed

    private void tfSearchBarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfSearchBarKeyReleased

        String keyword = tfSearchBar.getText().trim().toLowerCase();

        tableModel.setRowCount(0);

        for (StudentAcademicProfile s : failedStudents) {

            String id = s.getStudentID().toLowerCase();
            String name = s.getStudentName().toLowerCase();

            if (id.contains(keyword) || name.contains(keyword)) {
                tableModel.addRow(new Object[]{
                    s.getStudentID(),
                    s.getStudentName(),
                    s.getStudentMajor(),
                    String.format("%.2f", s.calculateCGPA()),
                    s.getStudentYear(),
                    s.getStudentEmail()
                });
            }
        }

    }//GEN-LAST:event_tfSearchBarKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FailedStudentListFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnViewCourseRecoveryPlan;
    private javax.swing.JButton jBtnClose;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel_Student_Failed;
    private javax.swing.JScrollPane jScrollPanel_Student_Failed;
    private javax.swing.JTable jTable_Student_Failed;
    private javax.swing.JTextField tfSearchBar;
    // End of variables declaration//GEN-END:variables
}
