package crsAppPackage;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author gilan
 */
public class FrameCourseRecoveryPlan extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrameCourseRecoveryPlan.class.getName());

    /**
     * Creates new form main_course_recovery_plan_frame
     */
    public FrameCourseRecoveryPlan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_Student_Failed = new javax.swing.JPanel();
        jScrollPanel_Student_Failed = new javax.swing.JScrollPane();
        jTable_Student_Failed = new javax.swing.JTable();
        jTextField_SearchBar2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton_Plan_Editor = new javax.swing.JButton();
        jButton_Milestone = new javax.swing.JButton();
        jCB_Batch_Edit = new javax.swing.JCheckBox();
        jRBFilterID = new javax.swing.JRadioButton();
        jRBFilterName = new javax.swing.JRadioButton();
        jRBFilterEmail = new javax.swing.JRadioButton();
        jRBFilterYear = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable_Student_Failed.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Major", "CGPA", "Year", "Email"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable_Student_Failed.setColumnSelectionAllowed(true);
        jTable_Student_Failed.setName("list_student_failed"); // NOI18N
        jScrollPanel_Student_Failed.setViewportView(jTable_Student_Failed);
        jTable_Student_Failed.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        javax.swing.GroupLayout jPanel_Student_FailedLayout = new javax.swing.GroupLayout(jPanel_Student_Failed);
        jPanel_Student_Failed.setLayout(jPanel_Student_FailedLayout);
        jPanel_Student_FailedLayout.setHorizontalGroup(
            jPanel_Student_FailedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPanel_Student_Failed)
        );
        jPanel_Student_FailedLayout.setVerticalGroup(
            jPanel_Student_FailedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPanel_Student_Failed, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE)
        );

        jTextField_SearchBar2.setText("jTextField1");

        jLabel3.setText("Search by StudentID or Name");

        jButton_Plan_Editor.setText("Plan Editor");

        jButton_Milestone.setText("Milestone");

        jCB_Batch_Edit.setText("Multiple Select");
        jCB_Batch_Edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCB_Batch_EditActionPerformed(evt);
            }
        });

        jRBFilterID.setText("ID");
        jRBFilterID.setToolTipText("");
        jRBFilterID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBFilterIDActionPerformed(evt);
            }
        });

        jRBFilterName.setText("Name");
        jRBFilterName.setToolTipText("");
        jRBFilterName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBFilterNameActionPerformed(evt);
            }
        });

        jRBFilterEmail.setText("Email");
        jRBFilterEmail.setToolTipText("");
        jRBFilterEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBFilterEmailActionPerformed(evt);
            }
        });

        jRBFilterYear.setText("Year");
        jRBFilterYear.setToolTipText("");
        jRBFilterYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBFilterYearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jRBFilterYear)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRBFilterEmail)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRBFilterName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRBFilterID))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jCB_Batch_Edit)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton_Milestone)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton_Plan_Editor))
                            .addComponent(jPanel_Student_Failed, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 90, Short.MAX_VALUE)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_SearchBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_SearchBar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRBFilterID)
                    .addComponent(jRBFilterName)
                    .addComponent(jRBFilterEmail)
                    .addComponent(jRBFilterYear))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel_Student_Failed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Plan_Editor)
                    .addComponent(jButton_Milestone)
                    .addComponent(jCB_Batch_Edit))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRBFilterIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBFilterIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRBFilterIDActionPerformed

    private void jRBFilterNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBFilterNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRBFilterNameActionPerformed

    private void jRBFilterEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBFilterEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRBFilterEmailActionPerformed

    private void jRBFilterYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBFilterYearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRBFilterYearActionPerformed

    private void jCB_Batch_EditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCB_Batch_EditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCB_Batch_EditActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrameCourseRecoveryPlan().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Milestone;
    private javax.swing.JButton jButton_Plan_Editor;
    private javax.swing.JCheckBox jCB_Batch_Edit;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel_Student_Failed;
    private javax.swing.JRadioButton jRBFilterEmail;
    private javax.swing.JRadioButton jRBFilterID;
    private javax.swing.JRadioButton jRBFilterName;
    private javax.swing.JRadioButton jRBFilterYear;
    private javax.swing.JScrollPane jScrollPanel_Student_Failed;
    private javax.swing.JTable jTable_Student_Failed;
    private javax.swing.JTextField jTextField_SearchBar2;
    // End of variables declaration//GEN-END:variables
}
